description: Templates e plugins para projetos Java 
name: community-spring-stack
display-name: Stack Spring 
picture: stack.png
category: Backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility: # Put a list of technologies compatible with the stack
  - Java
  - Spring
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies 
  - Docker 
  - AWS SQS
  - Springboot
  - Java
about: docs/about.md
use-cases:
  - title: Webflux + AWS SQS 
    content: docs/use-case.md
    stackfile: stackfiles/java-spring-webflux.yaml
